// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Start process to fill our calendar
	// (POST /start)
	StartCrossfitAgenda(ctx echo.Context) error
	// Status process
	// (GET /status)
	Status(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// StartCrossfitAgenda converts echo context to params.
func (w *ServerInterfaceWrapper) StartCrossfitAgenda(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.StartCrossfitAgenda(ctx)
	return err
}

// Status converts echo context to params.
func (w *ServerInterfaceWrapper) Status(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Status(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/start", wrapper.StartCrossfitAgenda)
	router.GET(baseURL+"/status", wrapper.Status)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5RUzWrkSAx+FaPdY5F2QnYJvi07cxjmEsgxDIPaltuVlKtqJDmhCX73QbbbndDOYS5N",
	"Yak+fT+qfoM9Ct2jdlDB7uUaHNSpzylSVIHqbXTQUOujV5+ifYD/DhQbtFPmlInV0/TdN/arx0xQgSj7",
	"eIBxdMD0a/BMDVSP1vPDnXrS/olqhdHBV+bEl4gNKm1gOuhJBA/bNVHUQd6V4tDviS+oLH1nMDfP2+L3",
	"sGJ+JGhOBZpJNtTiEBSqFoPQCrJPKRBGQznJaRP3qFDB4KP+ewtrr49KB6Nqniv6sClw9nkF+Rzj7ERD",
	"UrPPFiFUcM+pJpHi4eQAxaE3S14TP9sQBxa4dNTYEX2g97F9Hu0icWXvziavTl3aOzrokpiUkGoMdq7u",
	"yrsSHPjYpskDr8Gu/M9JpPVaLDvo4IVYZlXXV+VVabJTpojZQwXgIKN2kwU7UWSdIpyGvVkfo1nyrYHK",
	"ImY94a/wmVMz1Bb2I2DOwdfTjd2TpGhSmCSnKPM23JS3l2anZ+P0T1leluatdyB1R/30oP5maqGCv3bv",
	"ntxubhvNJxn6Hvl4olvkJUlNRetDKNLARY3ByM8LvzvvwIG2Vc/5/KHQDTUy1MalHUKxzvggziv18qnK",
	"hcm4rgcy43FDtg5y0r1UbcLMvFPNxlaoHtjr8cvHfy7M/uczHScyRrkjbMgSiNhPI5f6mUP23+k4OSmv",
	"eLB3VcGNrdnvAAAA//9geO1lNwUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
